### ISSUE TITLE
Ajouter le calque Cadastre ?

### ISSUE THREAD

**Issue by bagage** [osm-fr/presentoir-carte#1]
Est-ce que c'est possible de rajouter le tms du cadastre à la liste déjà présente ?

**Comment by sletuffe** [comment]
J'ai rien contre, mais je ne sais pas faire. Si quelqu'un ajoute le code, pas de problème

**Comment by grischard** [comment]
Rajouté dans 1ac3710e3e99d0ebe8cfaaf0164f3c2c18cbef8a
